PROGRAM = main
OBJS = main.o

CC = gcc
CFLAGS = -Wall -O2
LDFLAGS =

.SUFFIXES: .c .o

$(PROGRAM): $(OBJS)
	$(CC) -o $(PROGRAM) $^

.c.o:
	$(CC) $(CFLAGS) -c $<

.PHONY: clean
clean:
	$(RM) $(PROGRAM) $(OBJS)

